### ISSUE TITLE
Not working on hydro dam roads

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/CurbHeightAdjuster#2]
As shown in screenshot, the [Medium Dam Road](https://steamcommunity.com/sharedfiles/filedetails/?id=1939679056) is still at 30cm (other roads are all at custom 10cm):

![image](https://user-images.githubusercontent.com/1386719/145133123-993014f3-ff17-4117-b8da-99223eb4620c.png)

**Comment by algernon-A** [comment]
Confirmed - DamAI is not currently included in eligibility filter.  Segment shader is still valid.

**Comment by algernon-A** [comment]
Fixed in f060b597857847fc11902dc55ca3562be3249b99

**Comment by originalfoo** [comment]
Tested, works great now - thanks!
