### ISSUE TITLE
Big Parking Lot assets

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/CurbHeightAdjuster#5]
When the road surface is raised, it creates an issue with Big Parking Lot road assets (specifically the parking 'buildings' which are placed adjacent to them) - the parking spaces are still at original height (eg. 30cm depth) so cars sink in to the asphalt:

![image](https://user-images.githubusercontent.com/1386719/149248775-8de3d156-4e72-42ce-9a2f-0ecd4c3c980a.png)

In the image above, I've set my curb height to be 10 cm so the vehicles are sinking below asphalt by ~20cm. I suspect these assets are designed for -30cm road surface.

If possible, could CHA alter the assets to raise their parking spaces by same amount as road surface?

There's loads of assets for BPL roads which can be found in these collections:

* [Original BPL pack](https://steamcommunity.com/workshop/filedetails/?id=2111928014)
* [Legacy BPL addons](https://steamcommunity.com/workshop/filedetails/?id=2135245537)
* [Functional BPL addons](https://steamcommunity.com/workshop/filedetails/?id=2118342585)

I'm not sure what best approach would be, as its unlikely that there's a simple way to idenfity the affected assets - maybe needs a list of workshop ids or something?

> Note: I also checked the older [Parking Lot Roads](https://steamcommunity.com/sharedfiles/filedetails/?id=1285201733) assets (by Badi_Dea) and those seem to work fine due to different implementation approach (they are placed direct on road and conform to terrain height, I assume):
>  
> ![image](https://user-images.githubusercontent.com/1386719/149249667-a8fe2cc0-1408-49a8-8045-c6a8b7aa9c32.png)

**Comment by algernon-A** [comment]
The Parking Lot Roads carparks (building mesh and prop heights) are actually deliberately changed by the mod to match the new curb height.  I didn't do the same for Big Parking Lots as my initial testing suggested that it was unnecessary; looking at it now, my testing was obviously in error.

I'll extend the parking framework to include the BPL carparks as well.

**Comment by algernon-A** [comment]
Fixed in 2ce2d48f38c56fa41d644ef58983ecd83156c2f5
